export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_USER_LIST = "GET_USER_LIST";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";

export const TOGGLE_ACTIVE = "TOGGLE_ACTIVE";
